import { Product } from "./types";

export const products: Product[] = [
  {
    id: "p1",
    slug: "peptide-serum-eon-01",
    name: "EON.01 Peptide Serum",
    category: "Сыворотки",
    tagline: "Сигнал для клеток начать обновление",
    description:
      "Концентрированная сыворотка с комплексом из 7 пептидов и стабилизированным витамином C. Разработана в лаборатории EONAGE для запуска естественных процессов регенерации кожи. Клинически протестирована совместно с врачами-косметологами клиники.",
    volume: "30 мл",
    price: 128,
    oldPrice: 160,
    bonusPoints: 130,
    bestseller: true,
    rating: 4.9,
    reviews: 214,
    ingredients: ["Пептидный комплекс Matrixyl", "Витамин C 10%", "Гиалуроновая кислота", "Ниацинамид"],
    bottle: "dropper",
    tint: "ion",
  },
  {
    id: "p2",
    slug: "longevity-cream-night",
    name: "Longevity Night Cream",
    category: "Кремы",
    tagline: "Восстановление, пока вы спите",
    description:
      "Ночной крем с ретинальдегидом и церамидами для глубокого восстановления барьера кожи. Часть системы Science of Skin Longevity — основа домашнего ухода после процедур в клинике.",
    volume: "50 мл",
    price: 142,
    bonusPoints: 140,
    bestseller: true,
    rating: 4.8,
    reviews: 176,
    ingredients: ["Ретинальдегид", "Церамиды NP", "Пантенол", "Масло ши"],
    bottle: "jar",
    tint: "silver",
  },
  {
    id: "p3",
    slug: "ai-glow-day-fluid",
    name: "AI Glow Day Fluid",
    category: "Кремы",
    tagline: "Лёгкий уход, подобранный по данным вашей кожи",
    description:
      "Дневной флюид SPF 30, формула которого адаптирована под самые частые результаты AI Skin Analysis: обезвоженность, тусклость, микровоспаления. Быстро впитывается, не оставляет белого следа.",
    volume: "40 мл",
    price: 96,
    oldPrice: 118,
    bonusPoints: 95,
    isNew: true,
    rating: 4.7,
    reviews: 89,
    ingredients: ["SPF 30", "Ниацинамид", "Экстракт центеллы", "Антиоксидантный комплекс"],
    bottle: "pump",
    tint: "ion",
  },
  {
    id: "p4",
    slug: "deep-reset-cleanser",
    name: "Deep Reset Cleanser",
    category: "Очищение",
    tagline: "Первый шаг лабораторного протокола ухода",
    description:
      "Гель для умывания с аминокислотами и пребиотиками. Мягко очищает, сохраняя микробиом кожи. Используется как первый шаг протокола перед процедурами в клинике EONAGE.",
    volume: "150 мл",
    price: 54,
    bonusPoints: 50,
    rating: 4.6,
    reviews: 132,
    ingredients: ["Аминокислотный комплекс", "Пребиотики", "Пантенол"],
    bottle: "tube",
    tint: "silver",
  },
  {
    id: "p5",
    slug: "hard-truth-retinol",
    name: "Hard Truth Retinol 0.3%",
    category: "Сыворотки",
    tagline: "Жёсткая правда для кожи, которая готова к результату",
    description:
      "Ночная сыворотка с инкапсулированным ретинолом 0.3%. Названа в честь кампании EONAGE о честности в косметологии — без обещаний, только измеримый результат через 28 дней.",
    volume: "30 мл",
    price: 134,
    oldPrice: 168,
    bonusPoints: 135,
    bestseller: true,
    rating: 4.9,
    reviews: 301,
    ingredients: ["Инкапсулированный ретинол 0.3%", "Сквалан", "Витамин E"],
    bottle: "dropper",
    tint: "gold",
  },
  {
    id: "p6",
    slug: "barrier-repair-mask",
    name: "Barrier Repair Mask",
    category: "Маски",
    tagline: "Скорая помощь после агрессивных процедур",
    description:
      "Успокаивающая маска на основе церамидов и пантенола. Рекомендована косметологами клиники в первые дни после инъекционных и аппаратных процедур.",
    volume: "75 мл",
    price: 78,
    bonusPoints: 75,
    isNew: true,
    rating: 4.8,
    reviews: 64,
    ingredients: ["Церамиды", "Пантенол 5%", "Аллантоин", "Бисаболол"],
    bottle: "jar",
    tint: "silver",
  },
  {
    id: "p7",
    slug: "acne-clear-complex",
    name: "Acne Clear Complex",
    category: "Сыворотки",
    tagline: "Протокол из клинического кейса «Как я вылечила акне»",
    description:
      "Точечная сыворотка с азелаиновой кислотой и цинком PCA. Разработана на основе реальных клинических протоколов лечения акне в EONAGE.",
    volume: "20 мл",
    price: 88,
    bonusPoints: 85,
    rating: 4.7,
    reviews: 148,
    ingredients: ["Азелаиновая кислота 10%", "Цинк PCA", "Салициловая кислота"],
    bottle: "dropper",
    tint: "ion",
  },
  {
    id: "p8",
    slug: "eonage-scanner-home",
    name: "EONAGE Scanner Home",
    category: "Домашние устройства",
    tagline: "AI Skin Analysis теперь у вас дома",
    description:
      "Компактная версия клинического сканера кожи. Полный чек-ап за 5 минут: увлажнённость, эластичность, пигментация, поры. Синхронизируется с приложением EONAGE и личным кабинетом клиники.",
    volume: "1 устройство",
    price: 690,
    oldPrice: 790,
    bonusPoints: 700,
    bestseller: true,
    rating: 5.0,
    reviews: 42,
    ingredients: ["AI-модуль анализа кожи", "5 параметров диагностики", "Синхронизация с приложением"],
    bottle: "device",
    tint: "silver",
  },
  {
    id: "p9",
    slug: "silk-body-elixir",
    name: "Silk Body Elixir",
    category: "Кремы",
    tagline: "Тот же язык науки — для тела",
    description:
      "Сухое масло для тела с комплексом пептидов и витамином E. Мгновенно впитывается, оставляя шёлковое сияние без липкости.",
    volume: "100 мл",
    price: 74,
    bonusPoints: 70,
    rating: 4.6,
    reviews: 57,
    ingredients: ["Пептидный комплекс", "Витамин E", "Масло виноградных косточек"],
    bottle: "pump",
    tint: "gold",
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, count = 4) {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .concat(products.filter((p) => p.id !== product.id && p.category !== product.category))
    .slice(0, count);
}
